server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: oAuth
          uri: lb://oAuth
          predicates:
           - Path=/api/oauth/**

        - id: course
          uri: lb://course
          predicates:
           - Path=/api/courses/**

        - id: module
          uri: lb://module
          predicates:
            - Path=/api/modules/**

        - id: subscription
          uri: lb://subscription
          predicates:
            - Path=/api/subscriptions/**

        - id: schedule
          uri: lb://schedule
          predicates:
              - Path=/api/schedules/**

        - id: attendance
          uri: lb://attendance
          predicates:
              - Path=/api/attendances/**

        - id: assessment
          uri: lb://assessment
          predicates:
              - Path=/api/assessments/**

        - id: submission
          uri: lb://submission
          predicates:
              - Path=/api/submissions/**

        - id: stakeholder
          uri: lb://stakeholder
          predicates:
              - Path=/api/register/**

#        - id: ui
#          uri: http://localhost:3000
#          predicates:
#            - Path=/ui/**
