server:
  servlet:
    context-path: /api
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8080/api/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin
