#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: false
#    fetch-registry: false
#  datacenter: colombo-SriLanka
#  environment: production
#server:
#  port: 8761
